version: 2.1

orbs:
  pantheon: pantheon-systems/pantheon@0.5.1
  pfe: pantheon-systems/front-end@dev:decoupled-bridge2
workflows:
  build_and_deploy_node_bridge:
    jobs:
      - pantheon/push:
          checkout: false
          clone_content: true
          pre-steps:
            - pfe/gh-status:
                state: "pending"
                target_url: $CIRCLE_BUILD_URL
                description: "Starting back-end CMS build"
                context: "pantheon/webops-backend"
            - checkout
            - run: echo "${CIRCLE_WORKFLOW_ID}" > private/CIRCLE_WORKFLOW_ID.txt           
          terminus_clone_env: "dev"             
          post-steps:
            # move this step into a job param
            - pfe/gh-status:
                state: "success"
                target_url: $MULTIDEV_SITE_URL
                description: "Back-end CMS deployed to Pantheon"
                context: "pantheon/webops-backend" 
      - pfe/frontity-build-and-deploy:
          pre-steps:
            - pfe/gh-status:
                state: "pending"
                target_url: $CIRCLE_BUILD_URL
                description: "Starting front-end framework build"
                context: "pantheon/webops-frontend"                
          post-steps:
            # move this step into a job param          
            - pfe/gh-status:
                state: "success"
                target_url: $GCP_ENDPOINT
                description: "Front-end framework deployed"
                context: "pantheon/webops-frontend"
                
          # @todo, this param should not be necessary.
          build-directory: "frontity"
