version: 2.1
orbs:
  pfe: pantheon-systems/front-end@dev:decoupled-bridge-cms-push2
workflows:
  build_and_deploy_node_bridge:
    jobs:
      - pfe/frontity-build-and-deploy
      - pfe/cms-push:
          terminus_clone_env: "dev" # @todo remove this setting once the live env is working
