version: 2.1

orbs:
  pantheon: pantheon-systems/pantheon@0.5.1
  cloudrun: circleci/gcp-cloud-run@1.0.2
  pfe: pantheon-systems/front-end@0.3.0

jobs:
  frontend_build_and_deploy:
    docker:
      - image: quay.io/pantheon-public/build-tools-ci:6.x
    steps:
      - checkout
      - run:
        # Set TERMINUS_ENV and related environment variables.
        # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment
      - cloudrun/init
      - setup_remote_docker
      - run:
          name: Authenticate docker registry
          command: gcloud beta auth configure-docker ${GOOGLE_COMPUTE_ZONE}-docker.pkg.dev
      - run:
          name: Build and deploy docker image
          command: | 
            cd frontity 
            docker build -t ${GOOGLE_COMPUTE_ZONE}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/${TERMINUS_SITE}/${TERMINUS_SITE}:${CIRCLE_SHA1:0:7} .
            docker push ${GOOGLE_COMPUTE_ZONE}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/${TERMINUS_SITE}/${TERMINUS_SITE}:${CIRCLE_SHA1:0:7}
      - run:
          name: Deploy to cloud run
          command: | 
            gcloud run deploy ${TERMINUS_SITE} --image ${GOOGLE_COMPUTE_ZONE}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/${TERMINUS_SITE}/${TERMINUS_SITE}:${CIRCLE_SHA1:0:7} \
            --region ${GOOGLE_COMPUTE_ZONE} --platform managed --memory 512Mi --allow-unauthenticated \
            --no-traffic --revision-suffix dev-${CIRCLE_SHA1:0:7} \
            --update-env-vars BACKEND_URL=${DEV_SITE_URL}
      - run:
          name: Update traffic labels
          command: | 
            gcloud beta run services update-traffic ${TERMINUS_SITE} \
            --region ${GOOGLE_COMPUTE_ZONE} --platform managed \
            --update-tags dev-${CIRCLE_SHA1:0:7}=${TERMINUS_SITE}-dev-${CIRCLE_SHA1:0:7}
      - run:
          name: Test deployed service
          command: | 
            GET_GCP_DEPLOY_ENDPOINT=$(gcloud beta run services describe ${TERMINUS_SITE} --platform managed --region ${GOOGLE_COMPUTE_ZONE} --format="value(status.address.url)")
            GCP_ENDPOINT=https://dev-${CIRCLE_SHA1:0:7}---${GET_GCP_DEPLOY_ENDPOINT:8}
            curl -s $GCP_ENDPOINT
            echo ${GCP_ENDPOINT} is ready 
              
workflows:
  build_and_deploy_node_bridge:
    jobs:
      - pantheon/push
      - frontend_build_and_deploy