version: 2.1

orbs:
  pantheon: pantheon-systems/pantheon@0.5.1
  gcp-cli: circleci/gcp-cli@1.8.5
  pfe: pantheon-systems/front-end@dev:frontity-node-bridge

workflows:
  build_and_deploy_node_bridge:
    jobs:
      - pantheon/push:
          terminus_clone_env: "dev"
      - pfe/frontity-monorepo-build-and-deploy
      - pfe/frontity-monorepo-connect-node-bridge:
          requires: 
            - pantheon/push
            - pfe/frontity-monorepo-build-and-deploy
      
