version: 2.1

orbs:
  pantheon: pantheon-systems/pantheon@0.5.1
  pfe: pantheon-systems/front-end@dev:removing-monorepo-param

workflows:
  build_and_deploy_node_bridge:
    jobs:
      - pantheon/push:
          checkout: false
          clone_content: true
          pre-steps:
            - pfe/gh-status:
                state: "pending"
                target_url: $CIRCLE_BUILD_URL
                description: "Starting Backend Build"
                context: "pantheon/webops-backend"
            - checkout
            - run: echo "${CIRCLE_WORKFLOW_ID}" > private/CIRCLE_WORKFLOW_ID.txt           
          terminus_clone_env: "dev"             
          post-steps:
            - pfe/gh-status:
                state: "success"
                target_url: $MULTIDEV_SITE_URL
                description: "Backend deployed to pantheon"
                context: "pantheon/webops-backend" 
      - pfe/frontity-build-and-deploy:
          pre-steps:
            - pfe/gh-status:
                state: "pending"
                target_url: $CIRCLE_BUILD_URL
                description: "Starting Frontend Build"
                context: "pantheon/webops-frontend"
                
          post-steps:
            - pfe/gh-status:
                state: "success"
                target_url: $GCP_ENDPOINT
                description: "Frontend deployed"
                context: "pantheon/webops-frontend"                             
          build-directory: "frontity"
